# Site settings
title: Wei Wang
header-img: "img/autumn.jpg"
tagline: "宁静致远"  
description: "不积跬步无以至千里"  
baseurl: ""
url: "http://byronwwang.github.io"  
#url: "http://localhost:4000"

# About/contact
owner: 
  name: "Wei"
  email: byronwwang@gmail.com
  bio: "菩提本无树，明镜亦非台"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.ico

#douban_username: Azeril
#twitter_username: Azeril_Lapland  
github_username: byronwwang  
#facebook_username: Azeril_Lapland  
#weibo_username: Azeril  
#zhihu_username: Azeril  

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
 input: GFM
highlighter: rouge

gems: 
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Wei"
      header-img: "img/bay.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments 
comments :
  provider : disqus
#  duoshuo :
#    short_name : byronwwang
  disqus :
      short_name : byronwwang

# Analytics and webmaster tools stuff goes here
# google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation

theme: jekyll-theme-slate